contact_links:
  - name: Questions or general discussion â“ğŸ—£ï¸
    url: https://github.com/executablebooks/markdown-it-py/discussions
    about: Use Disussions for general conversations that aren't meant for actionable Issues.
