name: benchmark

on:
  push:
    branches: [master]

jobs:
  benchmark-packages:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: install pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: '2.6'

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run package benchmarks
      run: tox -e py38-bench-packages -- --benchmark-min-rounds 20 --benchmark-json bench-packages.json

    # - name: Upload package data
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: bench-packages
    #     path: bench-packages.json
    #     if-no-files-found: error

    - name: Store benchmark result
      uses: aiidateam/github-action-benchmark@v3
      with:
        name: Parsing Benchmarks
        output-file-path: bench-packages.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        commit-msg-append: "[ci skip]"
        one-chart-groups: packages,plugins
        fail-on-alert: false
